---
- name: Alert user to variables needed
  hosts: ansible_host
  tasks:
  - name: Alert user to variables needed - clusterid
    debug:
      msg: "openshift_aws_clusterid={{ openshift_aws_clusterid }}"

  - name: Alert user to variables needed - region
    debug:
      msg: "openshift_aws_region={{ openshift_aws_region }}"

- name: Delete the master node group
  hosts: ansible_host
  tasks:
  - name: delete masters
    import_role:
      name: openshift_aws
      tasks_from: uninstall_masters.yml
