- name: Pre-requisites
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: MAINN TEST
    shell: . ../../demo/keystonerc && ansible-playbook --private-key ../../.ssh/id_rsa.pub --user openshift -i ../../demo/inventory ../../demo/openshift-ansible/playbooks/openstack/openshift-cluster/provision_install.yml -e openshift_repos_enable_testing=true
    args:
      executable: /bin/bash
