- name: Pre-requisites
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: MAINN TEST 3
    shell: . keystonerc && `whoami` &&ansible-playbook --private-key .ssh/id_rsa.pub --user openshift -i demo/inventory provision_install.yml -e openshift_repos_enable_testing=true
    args:
      executable: /bin/bash
