- name: Pre-requisites
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Check the prerequisites for cluster provisioning in OpenStack
    shell: . /var/lib/awx/demo/keystonerc && ansible-playbook --user openshift -i /var/lib/awx/demo/inventory /var/lib/awx/demo/openshift-ansible/playbooks/openstack/openshift-cluster/provision_install.yml -e openshift_repos_enable_testing=true
    args:
      executable: /bin/bash
